name: Deploy to Dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy (Dev)

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create .env.local
        run: |
          echo "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}" >> .env.local
          echo "CONTENTFUL_SPACE_ID=${{ secrets.CONTENTFUL_SPACE_ID }}" >> .env.local
          echo "CONTENTFUL_ACCESS_TOKEN=${{ secrets.CONTENTFUL_ACCESS_TOKEN }}" >> .env.local
          echo "CONTENTFUL_PREVIEW_API_TOKEN=${{ secrets.CONTENTFUL_PREVIEW_API_TOKEN }}" >> .env.local
          echo "NEXT_PUBLIC_VERCEL_ENV=preview" >> .env.local
          echo "NEXT_PUBLIC_GITHUB_DEPLOY_TOKEN=${{ secrets.NEXT_PUBLIC_GITHUB_DEPLOY_TOKEN }}" >> .env.local

      - name: Deploy to Azure Static Web Apps (Dev)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_BAY_0F7F6F503 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          output_location: "out"
